import { Box, Button, Dialog } from '@mui/material';
import { ZodErrorDisplay } from './zodErrorDisplay';
import React from 'react';
import { ZodError, ZodIssue } from 'zod';

export interface ZodErrorDialogProps {
  showDialog?: boolean;
  fieldNameMapper?: (issue: ZodIssue) => string|undefined;
  errors?: ZodError<any>;
  onDismissDialog?: () => void;
}

/**
 * Dialog component for displaying {@link ZodError}s
 * @param showDialog whether dialog should be displayed
 * @param fieldNameMapper custom field error message mapper to use (optional)
 * @param onDismissDialog callback for the keys/buttons to dismiss the dialog
 * @param errors errors to be displayed generated by zod safeParse
 */
export const ZodErrorDialog = ({
  showDialog,
  fieldNameMapper,
  onDismissDialog,
  errors
                               }: ZodErrorDialogProps) => {

  return (<Dialog
    fullWidth
    scroll={'paper'}
    open={!!showDialog}
    onClose={onDismissDialog}
    title={'Validation Error'}
     >
    <Box padding={'2em'}>
      Error validating alignment file
      <ZodErrorDisplay
        fieldNameMapper={fieldNameMapper}
        errors={errors} />
      <Box
        textAlign={'right'}
      >
        <Button onClick={onDismissDialog}>Close</Button>
      </Box>
    </Box>
  </Dialog>);
}
